In [1]:
import numpy as np

<H1>1. Make a numpy array</H1>

In [6]:
a = np.zeros(3)
print(a)
print(a.shape)

[ 0.  0.  0.]
(3,)


In [13]:
a = np.zeros((1,3))
print(a)
print(a.shape)

[[ 0.  0.  0.]]
(1, 3)


In [14]:
a[0] = 1

In [15]:
print(a)

[[ 1.  1.  1.]]


<h1>2. Transform a numpy array!!</h1>

In [16]:
a = np.arange(100)

In [17]:
a.shape

(100,)

<h1>3. Search a numpy array</h1>

<h1>4. Misc</h1>