In [1]:
import numpy as np

<H1>1. Make a numpy array</H1>

In [6]:
a = np.zeros(3)
print(a)
print(a.shape)

[ 0.  0.  0.]
(3,)


In [21]:
a = np.zeros((1,3))
print(a)
print(a.shape)
a[0] = 1
print(a) #Oops!!

[[ 0.  0.  0.]]
(1, 3)
[[ 1.  1.  1.]]


In [49]:
a = np.zeros((1,3))
print(a)
print(a.shape)
a[:,0] = 1
print(a) #Ok!!

[[ 0.  0.  0.]]
(1, 3)
[[ 1.  0.  0.]]


<h1>2. Transform a numpy array!!</h1>

In [29]:
a = np.arange(100)
print(a.shape)
a = a.reshape(10,10)
print(a.shape)

(100,)
(10, 10)


In [42]:
a = np.arange(10).reshape(1,10)
b = np.arange(10).reshape(1,10) +10

In [43]:
c = np.concatenate((a,b),axis =0)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)


In [48]:
c = np.concatenate((a,b),axis =1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)


<h1>3. Search a numpy array</h1>

In [57]:
a = np.array([1,2,3,4,6,3,2,3,6,4,5])
max_idx = a.argmax()
print(max_idx,a[max_idx])
print(max(a) == a[max_idx])

4 6
True


In [58]:
#To do multi dimention argmax!!

In [89]:
a = np.array([5,2,4,5,6,1,3,4,2]).reshape(-1,1)
args = np.argwhere(a>3)
print(args)
print("-"*20)
print(a[args],a[args].shape) # WTF!!?

[[0 0]
 [2 0]
 [3 0]
 [4 0]
 [7 0]]
--------------------
[[[5]
  [5]]

 [[4]
  [5]]

 [[5]
  [5]]

 [[6]
  [5]]

 [[4]
  [5]]] (5, 2, 1)


<h1>4. Misc</h1>

In [81]:
a = np.random.randn(1000)
print(np.mean(a),np.std(a))

-0.00734857046817 0.970390780035


In [80]:
np.random.randn(10)

array([ 1.59204628,  2.76613806,  0.79161954, -1.42777767,  0.93020051,
        0.68856377, -1.03682258,  1.21675596,  0.89839728, -0.10682395])

In [ ]:
"""
To do
infinite
sum
sort

"""