In [1]:
import numpy as np

<H1>1. Make a numpy array</H1>

In [6]:
a = np.zeros(3)
print(a)
print(a.shape)

[ 0.  0.  0.]
(3,)


In [21]:
a = np.zeros((1,3))
print(a)
print(a.shape)
a[0] = 1
print(a) #Oops!!

[[ 0.  0.  0.]]
(1, 3)
[[ 1.  1.  1.]]


In [49]:
a = np.zeros((1,3))
print(a)
print(a.shape)
a[:,0] = 1
print(a) #Ok!!

[[ 0.  0.  0.]]
(1, 3)
[[ 1.  0.  0.]]


<h1>2. Transform a numpy array!!</h1>

In [29]:
a = np.arange(100)
print(a.shape)
a = a.reshape(10,10)
print(a.shape)

(100,)
(10, 10)


In [42]:
a = np.arange(10).reshape(1,10)
b = np.arange(10).reshape(1,10) +10

In [43]:
c = np.concatenate((a,b),axis =0)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)


In [48]:
c = np.concatenate((a,b),axis =1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)


<h1>3. Search a numpy array</h1>

In [55]:
a = np.array([1,2,3,4,4,3,2,3,6,4])
max_idx = a.argmax()
print(max_idx,a[max_idx])
print(max(a) == a[max_idx])

8 6
True


<h1>4. Misc</h1>