In [1]:
#4章
import numpy as np

In [2]:
def mean_squared_error(y, t):
    return 0.5*np.sum((y-t)**2)

In [31]:
t=np.array([0,0,1,0,0,0,0,0,0,0])
y=np.array([0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0])
#mean_squared_error(t, y)

In [6]:
def cross_entropy_error(y, t):
    delta = 1e-7
    print(delta)
    return -np.sum(t*np.log(y+delta))

In [7]:
cross_entropy_error(y, t)

1e-07


0.510825457099338

In [16]:
y=np.array([0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0])

In [17]:
cross_entropy_error(y,t)

1e-07


2.302584092994546

In [19]:
from keras.datasets import mnist

In [20]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [29]:
x_train= x_train.reshape(60000,784)
x_test= x_test.reshape(10000,784)
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [62]:
train_size = x_train.shape[0]
print(train_size)
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
y_batch = y_train[batch_mask]

60000


In [49]:
arr = np.zeros((100, 10,10))
print(arr.shape)
arr_size = arr[0]
print(arr_size.shape)

(100, 10, 10)
(10, 10)


In [55]:
np.random.choice(train_size, 10)

array([  0,   0,   0,   0,   0,   0, 253,   0,   0,   0], dtype=uint8)

In [5]:
import numpy as np

In [4]:
import sys
print(sys.executable)

/usr/local/opt/python/bin/python3.7


In [6]:
#batch対応版
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t=t.reshape(1, t.size)
        y=y.reshape(1, y.size)
        
    batch_size=y.shape[0]
    return -np.sum(t*np.log(y))/batch_size

In [42]:
#本当にこれあってるのか？謎

def cross_entropy_error(y, t) :
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        print(t)
        print(y)
    batch_size = y.shape[0]
    print([np.arange(batch_size), t])
    return -np.sum(t*np.log(y[np.arange(batch_size), t])) / batch_size

In [25]:
t=np.array([0,0,1,0,0,0,0,0,0,0])
y=np.array([0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0])
arr = np.arange(4)

In [28]:
y[np.arange(4), t]

IndexError: too many indices for array

In [3]:
import numpy as np
a = np.arange(10)
b =[4,1,2]
c = a[b]

In [5]:
c

array([4, 1, 2])

In [6]:

b = [np.arange(3), ]

In [27]:
t = np.array([0,0,1,0,0,0,0,0,0,0])
t = t.reshape(1, t.size)
print(t)
ans = t[np.arange(3), t]
ans

[[0 0 1 0 0 0 0 0 0 0]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (1,10) 

In [28]:
ans = t[:3, t]

In [29]:
ans

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [43]:
#ここマジでわからん
batch_size=5
cross_entropy_error(y, t)

[[0 0 1 0 0 0 0 0 0 0]]
[[0.1  0.05 0.6  0.   0.05 0.1  0.   0.1  0.   0.  ]]
[array([0]), array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])]


2.995732273553991

In [44]:
#損失関数を導入することによって、パラメタの微小な変化を捉えることができる

In [48]:
#4_3 数値微分
#微小な差分によって微分を求めることを数値微分という
#通常の微分は、解析的な微分という
#微分の悪い実装例
def diff(f, x):
    h=10e-4
    return (f(x+h)-f(x))/h

In [50]:
np.float32(1e-4)

1e-04

In [4]:
#まるめ誤差のために、hを非常に小さい値にできない
#中心差分を用いて実装する
def diff(f, x):
    h=1e-4
    return (f(x+h)-f(x-h))/(h*2)

In [1]:
#偏微分
#引数にnumpy配列が用いられることに注意
def function_2(x):
    return x[0]**2+x[1]**2

In [2]:
def function_tmp1(x0):
    return x0*x0+4.0**2.0

In [5]:
diff(function_tmp1, 3.0)

6.00000000000378

In [6]:
def function_tmp2(x1):
    return 3.0**2.0+x1*x1

In [7]:
diff(function_tmp2, 4.0)

7.999999999999119

In [1]:
#x1とx0の偏微分をまとめて計算

def numerical_gradient(f, x):
    h=1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        #f(x+h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        #f(x-h)の計算
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1-fxh2)/(2*h)
        x[idx] = tmp_val
        
    return grad