In [1]:
import numpy as np
from pprint import pprint

In [6]:
a = np.zeros(3)
pprint(a)
pprint(a.shape)
a[0]=1
pprint(a)

array([ 0.,  0.,  0.])
(3,)
array([ 1.,  0.,  0.])


In [14]:
a = np.zeros((1,3))
pprint(a)
pprint(a.shape)
a[:,1] = 1
pprint(a)

array([[ 0.,  0.,  0.]])
(1, 3)
array([[ 0.,  1.,  0.]])


In [15]:
a = np.ones((6,6))
pprint(a)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])


In [16]:
a = np.ones((6,6))
a[1:3, 1:3] = 0
pprint(a)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])


In [17]:
a = np.array([[1,2,3],[1,2,4]])
pprint(a)

array([[1, 2, 3],
       [1, 2, 4]])


In [ ]:
#今日はここまで！ねむい